import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Projects',
      items: [
        'projects/theia-deployment',
        'projects/theia-scale-tests',
        'projects/theia-shared-cache',
        'projects/theia-lsp-extension',
        'projects/theia-data-bridge',
        'projects/eduidec',
        'projects/theia-arc-runners',
        'projects/theia-workspace-garbage-collector',
      ],
    },
    {
      type: 'category',
      label: 'Contributions',
      items: [{type: 'autogenerated', dirName: 'contributions'}],
    },
  ],
};

export default sidebars;
